# NB: this book overwrites the whole file authorized_keys
---
- name: create user
  hosts: all
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{ user_installer }}"
        shell: /usr/bin/bash
    - name: make user sudo
      ansible.builtin.template:
        src: templates/sudoers-nopasswd.j2
        dest: /etc/sudoers.d/allow-{{ user_installer }}
        mode: 0220
        # validate: TODO: do some validation here


- name: copy public key 
  hosts: all
  #vars:
  #  - user_installer: installer
  tasks:
    - name: SSH Directory
      ansible.builtin.file:
        path: /home/{{ user_installer }}/.ssh
        state: directory
        mode: 0700
        owner: "{{ user_installer }}"
        group: "{{ user_installer }}"
    - name: Copy Key
      ansible.builtin.copy:
        src: ~/.ssh/id_rsa_ansible.pub
        dest: /home/{{ user_installer }}/.ssh/authorized_keys
        mode: 0600
        owner: "{{ user_installer }}"
        group: "{{ user_installer }}"

      

