#!/bin/bash
MARIADB_DATABASE=dbmovie
MARIADB_USER=movie
MARIADB_PASSWORD=password
MARIADB_PORT=3306
CONTAINER_NAME=mariadb_$MARIADB_DATABASE

docker exec -it $CONTAINER_NAME  mysql -u $MARIADB_USER -p$MARIADB_PASSWORD $MARIADB_DATABASE
